version: "3.7"

volumes:
  logs:
    driver: local
  my-db:

services:
  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 9191:80
    environment:
      PMA_USER: user
      PMA_PASSWORD: secret
  db:
    container_name: "dbserver"
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "quick_site"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  slim:
    container_name: "quick_site"
    image: arodax/php7.4-fpm
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/var/www
      - logs:/var/www/logs
